version: '3'
services: 
  db: 
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    env_file: .env
    volumes: 
      - ./datas:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports: 
      - 3336:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80