INSERT INTO `answer_proposed` (`question_id`, `answer_proposed`) VALUES
    (25, 'YES'),
    (25, 'NO'),
    (26, ''),
    (27, `Pas d'intégration à la fin de la période d'essai`),
    (27, `Interruption de la période d\'essai à votre initiative`),
    (27, `Interruption de la période d'essai à l'initiative de l'entreprise`),
    (27, `Changement d\'entreprise`),
    (27, 'Autre'),
    (28, '1'),
    (28, 'de 2 à 5'),
    (28, 'de 5 à 10'),
    (28, 'plus de 10'),
    (29, 'Angular'),
    (29, 'React'),
    (29, 'Vue'),
    (29, 'JS natif'),
    (29, 'Spring boot'),
    (29, 'JEE natif'),
    (29, 'Symfony'),
    (29, 'Laravel'),
    (29, 'PHP natif'),
    (29, 'autre framework PHP'),
    (29, 'Python'),
    (29, '.Net'),
    (29, 'autre framework frontend'),
    (29, 'autres technologies'),
    (30, 'YES'),
    (30, 'NO'),
    (31, '1'),
    (31, '2'),
    (31, '3'),
    (31, '4'),
    (31, '5'),
    (31, '6'),
    (31, '7'),
    (31, '8'),
    (31, '9'),
    (31, '10'),
    (32, 'DevOps'),
    (32, 'Admin Sys'),
    (32, 'Chef de Projet'),
    (32, ' Scrum master'),
    (32, 'Product Owner'),
    (32, 'UX/UI designer'),
    (32, 'autre'),
    (40, 'très mal'),
    (40, 'mal'),
    (40, 'normal'),
    (40, 'bien'),
    (40, 'très bien'),
    (41, 'insatisfait'),
    (41, 'peu satisfait'),
    (41, 'moyennement'),
    (41, 'satisfait'),
    (41, 'très satisfait'),
    (42, 'pas du tout'),
    (42, 'un peu'),
    (42, 'moyennement'),
    (42, 'plutôt'),
    (42, 'complètement'),
    (43, 'très difficile'),
    (43, 'difficile'),
    (43, 'moyen'),
    (43, 'facile'),
    (43, 'très facile'),
    (44, 'très mauvais'),
    (44, 'mauvais'),
    (44, 'passable'),
    (44, 'bon'),
    (44, 'excellent'),
    (45, 'très mauvaise'),
    (45, 'mauvaise'),
    (45, 'passable'),
    (45, 'bonne'),
    (45, 'très bonne'),
    (46, 'très mauvaise'),
    (46, 'mauvaise'),
    (46, 'passable'),
    (46, 'bonne'),
    (46, 'excellente'),
    (47, ''),
    (48, 'YES'),
    (48, 'NO');