INSERT INTO `answer_proposed` (`question_id`, `answer_proposed`) VALUES
    (25, 'YES'),
    (25, 'NO'),
    (26, ''),
    (27, `Pas d'intégration à la fin de la période d'essai`),
    (27, `Interruption de la période d\'essai à votre initiative`),
    (27, `Interruption de la période d'essai à l'initiative de l'entreprise`),
    (27, `Changement d\'entreprise`),
    (27, 'Autre'),
    (28, '1'),
    (28, 'de 2 à 5'),
    (28, 'de 5 à 10'),
    (28, 'plus de 10'),
    (29, 'Angular'),
    (29, 'React'),
    (29, 'Vue'),
    (29, 'JS natif'),
    (29, 'Spring boot'),
    (29, 'JEE natif'),
    (29, 'Symfony'),
    (29, 'Laravel'),
    (29, 'PHP natif'),
    (29, 'autre framework PHP'),
    (29, 'Python'),
    (29, '.Net'),
    (29, 'autre framework frontend'),
    (29, 'autres technologies'),
    (30, 'YES'),
    (30, 'NO'),
    (31, '1'),
    (31, '2'),
    (31, '3'),
    (31, '4'),
    (31, '5'),
    (31, '6'),
    (31, '7'),
    (31, '8'),
    (31, '9'),
    (31, '10'),
    (32, 'DevOps'),
    (32, 'Admin Sys'),
    (32, 'Chef de Projet'),
    (32, ' Scrum master'),
    (32, 'Product Owner'),
    (32, 'UX/UI designer'),
    (32, 'autre');